### ISSUE TITLE
Comparison Corridor Function next steps

### ISSUE THREAD

**Issue by jamgreen** [shiweipsu/Street-Improvement-Impact#1]
Change the sectors to add up...include all of the LEHD variables then add up the accommodations, retail etc for "Service" and pull out Food, Retail, Accommodations.

**Comment by shiweipsu** [comment]
Define service sectors and add up other sectors, pull out Retail, Food_Accom separately
by bafd9a84408435b28a1f581a289d8fcd6a323583
